### ISSUE TITLE
Add support for excluding folders

### ISSUE THREAD

**Issue by amberpixels** [zhensherlock/intellij-platform-git-stats-plugin#90]
E.g. i want to exclude "vendor" folder from git stats.
in git it can be done via:
`git log ....  -- . ':(exclude)vendor' `

**Comment by zhensherlock** [comment]
Thank you for the suggestion! Excluding specific folders is a useful feature, and we’ll consider adding support for it.

**Comment by zhensherlock** [comment]
The new version has been released, welcome to try it.
![image](https://github.com/user-attachments/assets/319ddbeb-047a-4b3b-832b-1685d6df6844)
![image](https://github.com/user-attachments/assets/55e3d9a8-1999-485f-82a6-f70d60767057)

**Comment by amberpixels** [comment]
thanks. works like a charm
